### ISSUE TITLE
MobiFlight crashes when analog input value can't be converted to a number

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1051]
**Describe the bug**
MobiFlight crashes when analog input value can't be converted to a number. Reported by Jaime in Discord.

```
Application: MFConnector.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.FormatException
   at System.Number.StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)
   at System.Number.ParseInt32(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   at MobiFlight.MobiFlightModule.OnAnalogChange(CommandMessenger.ReceivedCommand)
   at CommandMessenger.CmdMessenger.InvokeCallBack(MessengerCallbackFunction, CommandMessenger.ReceivedCommand)
   at CommandMessenger.CmdMessenger.HandleMessage(CommandMessenger.ReceivedCommand)
   at CommandMessenger.Queue.ReceiveCommandQueue.ProcessQueue()
   at CommandMessenger.AsyncWorker.<Start>b__20_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by neilenns** [comment]
Happens here: https://github.dev/MobiFlight/MobiFlight-Connector/blob/64cc17c0ee80e458d2ede81a3b3f6dcb6ebd9840/MobiFlight/MobiFlightModule.cs#L583-L584

**Comment by neilenns** [comment]
Another user in Discord reported MobiFlight crashing to desktop when pressing a button occasionally with an Uno. The call stack is the same, trying to convert string to an int in `OnButtonPress()`.
