### ISSUE TITLE
Exception in FindConnectedUsbDevices()

### ISSUE THREAD

**Issue by DocMoebiuz** [MobiFlight/MobiFlight-Connector#1074]
**Describe the bug**
A user reported exceptions during start up of Mobiflight Connector for the latest beta 9.6.0.4

```
************** Exception Text **************
System.IO.IOException: The device is not ready.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIODriveError(String driveName, Int32 errorCode)
   at System.IO.DriveInfo.get_VolumeLabel()
   at MobiFlight.MobiFlightCache.FindConnectedUsbDevices()
   at MobiFlight.UI.MainForm.CheckForFirmwareUpdates()
   at MobiFlight.UI.MainForm.ExecManager_OnModuleLookupFinished(Object sender, EventArgs e)
   at MobiFlight.ExecutionManager.mobiFlightCache_LookupFinished(Object sender, EventArgs e)
```

Full error message [message.txt](https://github.com/MobiFlight/MobiFlight-Connector/files/10457536/message.txt)

**Comment by DocMoebiuz** [comment]
[message.txt](https://github.com/MobiFlight/MobiFlight-Connector/files/10457536/message.txt)

**Comment by neilenns** [comment]
Thanks, will be easy enough to add a try/catch. Will tonight!

**Comment by neilenns** [comment]
Need to add a test for `IsReady` before reading the volume label. Probably also good to add a try/catch around it for extra protection.
