### ISSUE TITLE
System.Management.ManagementException trying to get connected ports

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1122]
Reported by a user in Discord. We crash here: https://github.dev/MobiFlight/MobiFlight-Connector/blob/1fa9794cb2d716bf8e5b38e26a3b7301188da88d/MobiFlight/MobiFlightCache.cs#L172-L173

Crash log:

```
System.Management.ManagementException: Invalid namespace 
   at System.Management.ThreadDispatch.Start()
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at MobiFlight.MobiFlightCache.getSupportedPorts()
   at MobiFlight.MobiFlightCache.<LookupAllConnectedComModulesAsync>d__31.MoveNext()
```

Reading around online it appears this happens when the WMI registry is somehow damaged or corrupted. There doesn't appear to be anything we can do other than catch the exception and move on. That would mean on this user's machine no COM devices would get detected though.

**Comment by neilenns** [comment]
Reported fixed by repairing the WMI registry with this command: `winmgmt /resetrepository`
