### ISSUE TITLE
Exception when loading corrupt config file

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1214]
**Describe the bug**
Mobiflight crashes with an unhandled exception if loading the config file contains invalid XML

**Steps To Reproduce**
Load the attached config file

**Expected behavior**
No crash. Error? Sure, but not a crash.

**Actual behavior**
Crash.

```
System.Xml.XmlException: '', hexadecimal value 0x03, is an invalid character. Line 1, position 15642.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline(Int32 startPos, Boolean expand, StringBuilder internalSubsetBuilder, Int32& charCount, EntityType& entityType)
   at System.Xml.XmlTextReaderImpl.ParseNumericCharRef(Boolean expand, StringBuilder internalSubsetBuilder, EntityType& entityType)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Data.DataTextReader.Read()
   at System.Data.XmlDataLoader.LoadColumn(DataColumn column, Object[] foundColumns)
   at System.Data.XmlDataLoader.LoadTable(DataTable table, Boolean isNested)
   at System.Data.XmlDataLoader.LoadData(XmlReader reader)
   at System.Data.DataSet.ReadXml(XmlReader reader, Boolean denyResolving)
   at MobiFlight.UI.MainForm._loadConfig(String fileName, Boolean merge)
   at MobiFlight.UI.MainForm._autoloadLastConfig()
   at MobiFlight.UI.MainForm._autoloadConfig()
   at MobiFlight.UI.MainForm.ExecManager_OnModuleLookupFinished(Object sender, EventArgs e)
   at MobiFlight.ExecutionManager.mobiFlightCache_LookupFinished(Object sender, EventArgs e)
   at MobiFlight.MobiFlightCache.<connectAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MobiFlight.ExecutionManager.<AutoConnectTimer_TickAsync>d__107.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

**Comment by neilenns** [comment]
Not sure why this is causing an unhandled exception as there's a try/catch in place at the point listed in the exception message. Will have to debug with the config file.

**Comment by JaimeLeon2** [comment]
The 0x03 hex character was actually encoded in the xml file. That is why it was impossible to find. 

The origin of this special character I traced it to a corrupt name label in one of my mega 2560 pro boards device configs in eeprom that was then passed to the Input config that used this device. MF never complained about this label having a special character.
