### ISSUE TITLE
Exception when loading config from an Uno

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1275]
[Reported by Zappysauce75 in Discord](https://discord.com/channels/608690978081210392/1106241639858569289/1142580307585933314)

```
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at MobiFlight.Config.Config.FromInternal(String value, Boolean throwException)
   at MobiFlight.MobiFlightModule.get_Config()
   at MobiFlight.MobiFlightModule.LoadConfig()
   at MobiFlight.MobiFlightCache.<>c__DisplayClass33_0.<connectAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

Looks like another place where we're missing a try/catch.

**Comment by neilenns** [comment]
There's a try/catch around it but it's catching two explicit exception types and there's no generic exception handler, so the OverflowException doesn't get handled.

https://github.com/MobiFlight/MobiFlight-Connector/blob/1f6d0552d8da341525a5a503d305bb2a7295ff07/MobiFlight/Config/Config.cs#L70
