### ISSUE TITLE
Exception thrown when saving config file

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1401]
Reported by user P. Santos in Discord. When attmepting to save the config file an exception is thrown:

```
System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)
   at System.IO.FileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.StreamWriter.Close()
   at System.Xml.XmlTextWriter.Close()
   at System.Xml.XmlDocument.Save(String filename)
   at MobiFlight.ConfigFile.SaveFile(DataSet outputConfig, DataSet inputConfig)
   at MobiFlight.UI.MainForm._saveConfig(String fileName)
   at MobiFlight.UI.MainForm.saveToolStripButton_Click(Object sender, EventArgs e)
```

This exception should get caught and an error message shown to the user instead of crashing.

**Comment by neilenns** [comment]
Apparently MobiFlight was run from the Downloads folder and the config was saved to Documents/MobiFlight. I still couldn't make the crash happen even doing that.

**Comment by DocMoebiuz** [comment]
The user should use the provided installer which installs into User AppData folders where no elevated permissions are required. 

Maybe it's a coincidence, or it has to do with going back and forth between different release versions.

**Comment by neilenns** [comment]
Sure, but this is still a place in the code where we have no exception handling in place and will crash.

**Comment by DocMoebiuz** [comment]
You're right. Documents is typically not a protected folder though. How weird.

**Comment by neilenns** [comment]
Windows has so many security things, it could have been a "this looks like a suspicious app" block or something 🤷‍♂️

It is easy enough to add a try catch, I opened a PR. At least we won't crash.
