### ISSUE TITLE
MobiFlight sometimes crashes on SimConnect.SetClientData()

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1483]
Jaime reported in Discord that he's seeing MobiFlight crash with this exception sometimes:

```
Exception Info: System.Runtime.InteropServices.COMException
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32, IntPtr)
   at Microsoft.FlightSimulator.SimConnect.SimConnect.SetClientData(System.Enum, System.Enum, Microsoft.FlightSimulator.SimConnect.SIMCONNECT_CLIENT_DATA_SET_FLAG, UInt32, System.Object)
   at MobiFlight.SimConnectMSFS.WasmModuleClient.SendWasmCmd(Microsoft.FlightSimulator.SimConnect.SimConnect, System.String, MobiFlight.SimConnectMSFS.WasmModuleClientData)
   at MobiFlight.ExecutionManager.Stop()
   at MobiFlight.ExecutionManager.ModuleCache_ModuleConnected(System.Object, System.EventArgs)
   at MobiFlight.MobiFlightCache+<SerialPortMonitor_PortAvailable>d__33.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()```

I swear I've seen this occasionally when running MobiFlight under the debugger as well.

**Comment by DocMoebiuz** [comment]
Is this during shut down?
Please add a link to the discord discussion.

**Comment by neilenns** [comment]
> Is this during shut down? Please add a link to the discord discussion.

No, it's just when you run MobiFlight, I think with AutoRun enabled.

[Start of discussion](https://discord.com/channels/608690978081210392/635953880122785824/1183884199728517272).

**Comment by neilenns** [comment]
@DocMoebiuz This is easy to reproduce:

1. Run MSFS2020. I made sure I was spawned in a plane somewhere.
2. Run MobiFlight with AutoRun enabled

Sometimes you have to run a few times before it will happen, but eventually it does. The crash is in WasmModuleClient.cs:47:

```C#
public static void SendWasmCmd(SimConnect simConnect, String command, WasmModuleClientData clientData)
{
    if (simConnect == null) return;

    simConnect.SetClientData(
       clientData.AREA_COMMAND_ID,
       (SIMCONNECT_DEFINE_ID)clientData.DATA_DEFINITION_ID,
       SIMCONNECT_CLIENT_DATA_SET_FLAG.DEFAULT,
       0,
       new ClientDataString(command)
    );
}
```

The command being sent is `MF.SimVars.Clear`. Here's the `clientData`:

<img width="400" alt="image" src="https://github.com/MobiFlight/MobiFlight-Connector/assets/9524118/35e0c70a-73fc-4b58-b926-ac069038dc0e">
