### ISSUE TITLE
AutoRun crashes and weird behavior with orphaned serials

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#1484]
**Describe the bug**
Because of reports from other users in Discord, I tested the AutoRun feature.  Multiple attempts resulted in multiple crashes to desktop.  Some other times, five out of seven boards are reported as orphaned serials.  AutoRun does not go into Run Mode.

**Steps To Reproduce**
1. Enable AutoRun (disable Minimize to Tray on AutoRun).
2. Exit and restart Mobiflight with seven boards already connected.
3. Mobiflight crashes to desktop half of the time with following Event Viewer log
```
Application: MFConnector.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32, IntPtr)
   at Microsoft.FlightSimulator.SimConnect.SimConnect.SetClientData(System.Enum, System.Enum, Microsoft.FlightSimulator.SimConnect.SIMCONNECT_CLIENT_DATA_SET_FLAG, UInt32, System.Object)
   at MobiFlight.SimConnectMSFS.WasmModuleClient.SendWasmCmd(Microsoft.FlightSimulator.SimConnect.SimConnect, System.String, MobiFlight.SimConnectMSFS.WasmModuleClientData)
   at MobiFlight.ExecutionManager.Stop()
   at MobiFlight.ExecutionManager.ModuleCache_ModuleConnected(System.Object, System.EventArgs)
   at MobiFlight.MobiFlightCache+<SerialPortMonitor_PortAvailable>d__33.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

```
Other times when it doesn't crash, five out of seven boards are reported as orphaned serial.
Only in one out of 6 starts did MFConnector correctly go into Run Mode.

![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/86563553/ea8547f1-ea3e-40e4-9b13-d0c78fcb5c0e)

Noticed that if the orphaned serial dialog is left open some time, Mobiflight tries to go into Run Mode for half a second then back to Stop Mode.  When exiting orphaned serial (wihtout assigning any serials), all the boards have been recognized and are working, but Mobiflight stays in stop mode.

When the orphaned serial dialog appears and I exit out of it quickly, then I noticed that Mobiflight waits about 5 seconds and enters Run Mode.

This shows AutoRun light bulb is enabled, but Mobiflight started and did not go into Run Mode. 

![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/86563553/5a47c9e4-d88c-4097-909d-9c1efef93462)

**Expected behavior**
With AutoRun enabled, Mobiflight enters Run Mode as soon as it starts.

**Actual behavior**
Mobiflight crashes to desktop.  Other times some boards (5 out of 7) are reported as orphaned serials.  

**Details**
 - MobiFlight Version: 10.0
 - FlightSim: MSFS2020
 - AddOn: FBW A320 Dev

**Additional context**
This behavior was only seen when AutoRun was enabled.  Orphaned serials continued to be reported after disabling AutoRun, but normal behavior was restored after rebooting the PC.

**Comment by neilenns** [comment]
@JaimeLeon2 Can you check your logs and see if you have any Errors showing?

**Comment by neilenns** [comment]
Possibly related [comment](https://discord.com/channels/608690978081210392/1178809382696386611/1184092283918897153) from Discord:

> Before I also launched MF after launching SIM (via FSUIPC, section [Programs])! But now MF needs to be launched before the “initialization” (I don’t know what word to use) of SIM. For example. I put MF first in the [Programs] list in FSUIPC.ini. Now the MF has time to boot, then the SIM is fully loaded and the MF turns on the AutoRun function.
