### ISSUE TITLE
Crash with unhandled IndexOutOfRangeException (AutoRun is enabled)

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1485]
I don't have steps to reproduce this, but I'm using the Mobiflight 10.0 release and have AutoRun enabled. I went to go turn on my plane power and the switch didn't do anything. I realized MobiFlight crashed, this is what event viewer shows:

```
Application: MFConnector.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Add(System.__Canon)
   at MobiFlight.MobiFlightCache+<SerialPortMonitor_PortAvailable>d__33.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by DocMoebiuz** [comment]
Probably fixed with: https://github.com/MobiFlight/MobiFlight-Connector/pull/1487
