### ISSUE TITLE
MobiFlight quits after start up

### ISSUE THREAD

**Issue by DocMoebiuz** [MobiFlight/MobiFlight-Connector#1506]
**Describe the bug**
```
Application: MFConnector.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
   at System.Windows.Forms.Control.Invoke(System.Delegate, System.Object[])
   at MobiFlight.UI.MainForm.ExecManager_OnInitialModuleLookupFinished(System.Object, System.EventArgs)
   at MobiFlight.ExecutionManager.mobiFlightCache_LookupFinished(System.Object, System.EventArgs)
   at MobiFlight.MobiFlightCache+<CheckIfLookUpFinished>d__34.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at MobiFlight.MobiFlightCache+<SerialPortMonitor_PortAvailable>d__33.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Steps To Reproduce**
1. Start MobiFlight

**Expected behavior**
Start up should finish just fine

**Actual behavior**
It closes unexpectedly

**Details**
 - MobiFlight Version: 10.0.2

**Additional context**
I don't know what conditions lead to this problem.

**Comment by DocMoebiuz** [comment]
This was related to custom device configs which were not registered in the official version yet. probably similar to #1495
