### ISSUE TITLE
MobiFlight Connector crashes on startup with MiniCockpit miniFCU connected

### ISSUE THREAD

**Issue by ngreatorex** [MobiFlight/MobiFlight-Connector#1585]
**Describe the bug**
Every time I open MobiFlight Connector (I've tried v10.0.2 and v10.0.2.3 beta), after choosing to install the WASM module and to participate in the feedback program, the application crashes and disappears. In the Application event log I can see a .NET Runtime error with an unhandled exception (see below).

**Steps To Reproduce**
1. Connect miniFCU to PC
2. Open MobiFlight Connector
3. Close release notes window
4. Install WASM module
5. Accept the feedback program

**Expected behavior**
1. Application to load to main screen as normal

**Actual behavior**

1. Application crashes and window closes with no error message
2. Event log contains:
```
Application: MFConnector.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at CommandMessenger.Transport.Serial.SerialTransport.Connect()
   at CommandMessenger.CommunicationManager.Connect()
   at MobiFlight.MobiFlightModule.Connect()
   at MobiFlight.MobiFlightCache+<>c__DisplayClass33_0.<SerialPortMonitor_PortAvailable>b__0()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at MobiFlight.MobiFlightCache+<SerialPortMonitor_PortAvailable>d__33.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Details**
 - MobiFlight Version: 10.0.2.3 beta
 - FlightSim: MSFS2020
 - AddOn: Irrelevant, I don't get that far.

**Additional context**
Cloning the project and opening in Visual Studio I can see this is caused by the throw here: https://github.com/MobiFlight/MobiFlight-Connector/blob/af4f83d8bb99683df42e75fd3b7cb3de84b784e3/CmdMessenger/CommandMessenger.Transport.Serial/SerialTransport.cs#L71
For some reason on my system, the port name is an empty string, causing the check to fail. I will continue to look into why this is.
At a minimum, there should be some exception handling around the call to Connect() to prevent the application crashing completely.

**Comment by ngreatorex** [comment]
I've worked out that this occurs because I had renamed the "FriendlyName" for the USB device to remove the COM number. 

I can accept that this is not a supported use case I guess, although parsing the name for the COM port doesn't strike me as a great idea!
