### ISSUE TITLE
Crash in DeviceMonitor

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1600]
[Reported by a user in Discord](https://discord.com/channels/608690978081210392/1196544053504921630)

Version: 10.1.0

Crashes with an unhandled exception on startup:

```
************** Exception Text **************
System.Management.ManagementException: Недопустимый класс 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementEventWatcher.Start()
   at MobiFlight.Monitors.DeviceMonitor.<Start>d__14.MoveNext()
```

The exception error translates to `Invalid Class`.

**Comment by neilenns** [comment]
@Koseng looks like you did this change in 10.1. Not sure why it would be crashing, but at a minimum needs some try/catch I guess.

**Comment by neilenns** [comment]
I had someone with wmi corruption issues when I did the original port detection work, forgot about that.

We should try/catch this and log an error so we don't crash. I think at one point I even added a warning this might be the cause? I'll go back and look.

**Comment by Koseng** [comment]
Ok the link helped. Problem is resolved. 
If we now know the reason, we could keep the exception. Or better catch the exception and show a box with the probable problem. Only logging I don't like. I like if there is a real problem that it actively shows.

**Comment by neilenns** [comment]
@Koseng I fixed essentially this same bug a year ago, see https://github.com/MobiFlight/MobiFlight-Connector/pull/1126/files?diff=unified&w=1 for the fix and the logged message we went with.

**Comment by Koseng** [comment]
@neilenns cool. Ok let's do something like that and an additional messagebox would be nice I think.

**Comment by neilenns** [comment]
I think message box is too much work for a case we've only seen twice in a year, especially if it can happen any time the background process runs 😅 But I'll leave it up to @DocMoebiuz

**Comment by neilenns** [comment]
We need to get this old code added back in. I'm pretty sure another user is hitting [a crash related to this in Discord](https://discord.com/channels/608690978081210392/1226034435900837959). We don't need fancy dialogs, just get the try/catch in with a logged error so we don't crash.

**Comment by neilenns** [comment]
Confirmed it was the same problem even though the exception was different and running the repair command fixed it.

**Comment by neilenns** [comment]
Another user in Discord hit this and we wasted an overnight period trying to figure out what was going wrong. We really need to put this catch back in.

**Comment by neilenns** [comment]
Another user hit this today. @DocMoebiuz @Koseng the old try/catch needs to be added back in.

**Comment by neilenns** [comment]
PR opened.
